<a href="https://colab.research.google.com/github/Haris-09/Python-Programming/blob/main/Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

file_path = '/content/drive/My Drive/NAVTCC: Data Science & AI' # Replace with your file path
books = pd.read_csv(file_path+'/books_01.csv')
books.head()

,Title,Author,Genre,Height,Publisher,Ratings
0,Fundamentals of Wavelets,"Goswami, Jaideva",signal_processing,228,Wiley,4.9
1,Data Smart,"Foreman, John",data_science,235,Wiley,1.2
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin,1.8
3,Superfreakonomics,"Dubner, Stephen",economics,179,HarperCollins,1.8
4,Orientalism,"Said, Edward",history,197,Penguin,4.3

In [4]:
# How many types of Books we have
books.Genre.unique()

array(['signal_processing', 'data_science', 'mathematics', 'economics',
       'history', 'science', 'psychology', 'fiction', 'computer_science',
       'nonfiction', 'philosophy', 'comic'], dtype=object)

In [5]:
books.Genre.nunique()

12

In [6]:
books.describe()

           Height     Ratings
count  211.000000  211.000000
mean   206.056872    2.971564
std     26.828141    1.099111
min    160.000000    1.000000
25%    180.000000    2.100000
50%    199.000000    3.000000
75%    229.500000    3.900000
max    283.000000    5.000000

In [7]:
# How many books are there in each category of Genre
books.Genre.value_counts()

Genre
fiction              64
nonfiction           30
history              26
data_science         17
philosophy           17
science              14
comic                13
computer_science     11
economics            10
mathematics           5
signal_processing     3
psychology            1
Name: count, dtype: int64

In [9]:
# Average grading of each category in genre
books.groupby('Genre')['Ratings'].mean()

Genre
comic                2.915385
computer_science     2.900000
data_science         2.958824
economics            2.820000
fiction              2.923437
history              2.719231
mathematics          2.800000
nonfiction           3.310000
philosophy           3.211765
psychology           2.200000
science              2.692857
signal_processing    4.366667
Name: Ratings, dtype: float64