<a href="https://colab.research.google.com/github/Haris-09/Python-Programming/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/NAVTCC: Data Science & AI/student_data.csv')
df.head()

,StudentID,Name,Age,Gender,Department,GPA,CreditsCompleted,Email
0,S1000,Brett Anderson,19,Female,Computer Science,3.78,115,stephaniezimmerman@lara-webb.com
1,S1001,Melissa Rhodes,18,Female,Business,3.48,72,thomasbenjamin@hotmail.com
2,S1002,Spencer Solomon,22,Female,Computer Science,2.31,109,nicoleflores@hotmail.com
3,S1003,Jeremy Hill,21,Male,Computer Science,2.56,70,daniellebarnes@hotmail.com
4,S1004,Brian Campbell,21,Male,Electrical,2.42,114,aaronjohnson@gmail.com

In [7]:
df.describe()

              Age         GPA  CreditsCompleted
count  100.000000  100.000000        100.000000
mean    21.280000    3.003200         89.450000
std      2.132386    0.604274         30.419085
min     18.000000    2.060000         30.000000
25%     19.000000    2.465000         66.750000
50%     21.000000    2.910000         89.500000
75%     23.000000    3.552500        115.000000
max     25.000000    3.970000        140.000000

In [8]:
df['Name']

0          Brett Anderson
1          Melissa Rhodes
2         Spencer Solomon
3             Jeremy Hill
4          Brian Campbell
             ...
95            Tanya Kelly
96    Mrs. Suzanne Morrow
97             Joshua Lee
98        Alexander Hanna
99         Sandra Wiggins
Name: Name, Length: 100, dtype: object